specfile_path: packaging/epel/convert2rhel.spec
synced_files:
    - packaging/epel/convert2rhel.spec
    - .packit.yaml
upstream_package_name: convert2rhel
downstream_package_name: convert2rhel
upstream_project_url: https://github.com/oamg/convert2rhel

jobs:
- job: copr_build
  metadata:
    targets:
    - epel-6-x86_64
    - epel-7-x86_64
  trigger: pull_request
- job: copr_build
  metadata:
    branch: master
    targets:
    - epel-6-x86_64
    - epel-7-x86_64
  trigger: commit
  actions:
    post-upstream-clone:
    - rpmdev-bumpspec --comment='latest upstream build' ./packaging/epel/convert2rhel.spec
